### PR TITLE
Prevent segfaulting when file does not exist.

### LINKED ISSUE #5: segmentation fault when DB file doesn't exist
```
› node
> var geoip = require('node-geoip2')
undefined
> geoip.init("./foo-file-dne")
zsh: segmentation fault  node
blimmer:~/code/server (develop ✗)
› node
> var geoip = require('node-geoip2')
undefined
> geoip.init("/tmp/GeoLite2-City.mmdb")
MMDB {}
```

Environment:
OS X 10.11.3
Node 4.2.6
node-geoip2 0.10.1

### PR DESCRIPTION
**Pull request by blimmer**
Fixes #5.

### CODE REVIEW

File: node-geoip2.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 
 var mmdb = require('./lib/node_mmdb.node');
 var path = require('path');
+var exists = require('exists-sync');
```
Comment (blimmer) [inline node-geoip2.js]: Since `fs.existsSync` is deprecated, I used this microlibrary that accomplishes the same thing in a supported fashion.

**Comment by davidtsai** [comment]
Good catch, thanks for contributing!

**Comment by davidtsai** [comment]
Actually this is a bug in the native code.  Fixed it properly in the C++ code.
